version: "3.8"

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamo_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  dynamo_data:
